[package]
name = "installtool"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9"

[target.'cfg(target_arch = "x86_64")'.dependencies]
limine = "0.2"
x86_64 = "0.15"
x86 = "0.52"

[profile.release]
opt-level = "z"
lto = true
strip = true